#pragma once

#define MATRIX_ROWS 8
#define MATRIX_COLS 17

#define DIODE_DIRECTION COL2ROW

#define DEBOUNCE 5

#define LOCKING_SUPPORT_ENABLE
#define LOCKING_RESYNC_ENABLE

#define STM32_BOOTLOADER_ADDRESS 0x1FFFF000
