MCU = STM32F103
BOARD = GENERIC_STM32F103C6
BOOTLOADER = stm32duino

BUILD_EXAMPLES = no

SRC += matrix.c

QUANTUM_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
