#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC,  KC_1,    KC_F4,   KC_G,    KC_H,    KC_F6,   KC_QUOT, KC_NO,   KC_F11,  KC_PSCR, KC_PGDN, KC_END,  KC_UP,   KC_SPC,  KC_NO,   KC_NO,   KC_NO,
        KC_2,    KC_3,    KC_4,    KC_7,    KC_8,    KC_9,    KC_0,    KC_F5,   KC_F10,  KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_A,    KC_S,    KC_D,    KC_F,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_BSLS, MO(1),   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_RGUI, KC_RSFT, KC_NO,
        KC_Z,    KC_X,    KC_C,    KC_V,    KC_M,    KC_COMM, KC_DOT,  KC_RCTL, KC_ENT,  KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
        KC_GRV,  KC_F1,   KC_F2,   KC_5,    KC_EQL,  KC_F8,   KC_BSLS, KC_LCTL, KC_F9,   KC_NO,   KC_PGUP, KC_HOME, KC_INS,  KC_DEL,  KC_NO,   KC_NO,   KC_NO,
        KC_TAB,  KC_CAPS, KC_F3,   KC_T,    KC_Y,    KC_RBRC, KC_F7,   KC_LBRC, KC_BSPC, KC_Q,    KC_W,    KC_E,    KC_R,    KC_U,    KC_LGUI, KC_LSFT, KC_NO,
        KC_I,    KC_O,    KC_P,    KC_B,    KC_PAUS, KC_N,    KC_SCRL, KC_SLSH, KC_NO,   KC_F12,  KC_RALT, KC_NO,   KC_LEFT, KC_RGHT, KC_DOWN, KC_NO,   KC_NO
    ),
    [1] = LAYOUT(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
};
